#!/bin/sh
                                                                                                                                                                             
NAME=tee-substrate-service
DAEMON=/sbin/$NAME
PIDFILE="/var/run/$NAME.pid"                                                                                                                                               
SSD_OPTIONS="--background --oknodo --quiet --exec $DAEMON"
DESC="TEE substrate service"
                                                                                                                                                                             
start() {                                                                                                                                                                    
        echo -n "Starting $DESC: "
        start-stop-daemon -p "$PIDFILE" --start $SSD_OPTIONS
        status=$?
        if [ "$status" -eq 0 ]; then
                echo "OK"
        else
                echo "FAIL"
        fi
        return "$status"
}

stop() {
        printf 'Stopping %s: ' "$DESC"
        start-stop-daemon -K -q -p "$PIDFILE"
        status=$?
        if [ "$status" -eq 0 ]; then
                echo "OK"
        else
                echo "FAIL"
        fi
        return "$status"
}

restart() {
        stop
        sleep 1
        start
}

case "$1" in
        start|stop|restart)
                "$1";;
        reload)
                # Restart, since there is no true "reload" feature (does not
                # reconfigure/restart on SIGHUP, just closes all open files).
                restart;;
        *)
                echo "Usage: $0 {start|stop|restart|reload}"
                exit 1
esac

exit 0
