name: CI
on: [push]

jobs:
  build_dk2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Blocked mirror workaround
      run: echo "1.1.1.1 invisible-mirror.net" | sudo tee -a /etc/hosts
    - name: Build image
      run: |
        ./tools/optee/gen_keys.sh
        make git-reset
        make dk2

  build_imx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Blocked mirror workaround
      run: echo "1.1.1.1 invisible-mirror.net" | sudo tee -a /etc/hosts
    - name: Build image
      run: |
        ./tools/optee/gen_keys.sh
        make git-reset
        make imx8mmevk
